/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MiqoraiRouteImport } from './routes/miqorai'
import { Route as IndexRouteImport } from './routes/index'

const MiqoraiRoute = MiqoraiRouteImport.update({
  id: '/miqorai',
  path: '/miqorai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/miqorai': typeof MiqoraiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/miqorai': typeof MiqoraiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/miqorai': typeof MiqoraiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/miqorai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/miqorai'
  id: '__root__' | '/' | '/miqorai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MiqoraiRoute: typeof MiqoraiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/miqorai': {
      id: '/miqorai'
      path: '/miqorai'
      fullPath: '/miqorai'
      preLoaderRoute: typeof MiqoraiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MiqoraiRoute: MiqoraiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
